about.html
This implements two things that came out of discussions at the .Astronomy 6 conference:
* A more firm/direct wording about citing the astropy paper
* A mention of how to use badges for projects that use Astropy (closes #48 )
cc @astrofrog
=> Dotastro ack updates

affiliated/index.html, affiliated/registry.json
This does just what it says: adds `imexam` to the registry of affiliated packages.
A few questions for @sosey before this is ready to be merged: 
1. I've classified this as "not stable", which just means that it's under active development.  Do you agree with that, or do you think it should be considered "stable".
2. Is there a PyPI entry?  Would you be willing to put it up there so people can ``pip install`` it?  It's fine if it's just an initial "development version".
3. You've had a chance to look over the description at the bottom of http://affiliated.astropy.org, right? So you know what I mean here by "provisional"?
cc @astrofrog
=> add imexam as affiliated package

index.html
This just updates index.html to reflect that 1.0.1 is out, rather than saying the latest is 1.0
I also updated the stable branch in the main repo to be v1.0.1 and set readthedocs to build a version for 1.0.1.  @embray, can you try to ping me (or @astrofrog) with a reminder to do the RTD stuff when you do bugfix releases?  That makes it easier to keep the stuff tightly in sync.
This is pretty trivial so I'll merge it immediately to keep things up-to-date, but I thought I should PR it just to make sure the record is there.
=> update index to v1.0.1

affiliated/registry.json
This PR adds `gwcs` to the affiliated package registry to make it easier to find.
@eteq @astrofrog – OK?
@nden – You should register the name `gwcs` on PyPI to make sure it's still available when you want to make a release.
=> Add gwcs to affiliated package registry

index.html
In master right now (and hence on the astropy.org site), the front page and all the other pages have slightly different sized "astropy" text (in the upper-left corner). This PR adjusts it so that they're all the same.
@mdboom - the git history says you set this up as part of #58 - was there some reason this was supposed to be different, or was this just an oversight?
=> Fix astropy logo so that index page matches other pages

affiliated/registry.json
Based on an email discussion a little while back with @ChrisBeaumont and @perrygreenfield, I think we agreed that glue should be an affiliated package. I think this is a good time to make sure we also understand what the implications of being an affiliated package are. So just to be clear, listing glue as an affiliated package does not exclude having it also be affiliated with other projects (e.g. outside astronomy), correct? In my view, the key sentence is the following (from our website):
> ... but has requested to be included as part of the Astropy project’s community. **These packages are expressing an interest in Astropy’s goals of improving reuse, interoperability, and interface standards for python astronomy and astrophysics packages.**
Because glue is also intended for use outside …
=> Added glue as an affiliated package

affiliated/index.html, js/functions.js
This fixes #80 and also generally makes the table-populating stuff more robust.  The result can be seen at http://eteq.github.io/astropy.github.com/affiliated/ (it's visually the same as the current version, but with affiliated and provisional swapped, as they should be to fix #80)
=> clean up affiliated table js code

affiliated/index.html, affiliated/registry.json
This makes a change to the affiliated packages site to remove the "Other packages" section.  It's been out-of-date for a while... I think the intent was to be text descriptions of the packages that are not "featured", but the number of packages has grown enough that that has become impractical (or at least it's not getting done).  So this just removes it.
To replace this, it might make sense to add a ``description`` section to the JSON registry and the package table. (I think @embray suggested this at some point?)  But until then I think it's better to remove this rather than leave it just very incomplete (and suggesting some of the packages are more special than others).
cc @astrofrog
=> remove Other Packages section

affiliated/index.html, css/style.css
As part of the provisional package review process, the coordination committee concluded we should add an expectation of python 3.x compatibility to the affiliated package standard.  This PR just adds that to the list of affiliated package standards.
cc @astrofrog @perrygreenfield
=> add py3.x requirement for affiliated package standards

affiliated/registry.json
Hi,
I am the author of the python package "python-cpl". This package is basically a small framework to process [ESO pipelines for the VLT instruments](http://www.eso.org/sci/software/pipelines/).
* The package uses astropy.io.fits for the file handling.
* documentation is available
* CI tests cover ~90% of the code
URLs:
* [PyPI](https://pypi.python.org/pypi/python-cpl)
* [Documentation](http://python-cpl.readthedocs.org/)
* [Github](https://github.com/olebole/python-cpl)
* [Travis](https://travis-ci.org/olebole/python-cpl)
I would like to ask whether the package could get the status of an Astropy affiliated package. I will also post this on the astropy-dev mailing list.
Best regards
Ole
=> Add python-cpl to affiliated packages

affiliated/index.html, affiliated/registry.json
This was suggested as part of the provisional package review process.  It removes astropysics (which really duplicates a lot of astropy functionality), but adds an "other packages" section.   You can see what this looks like at http://eteq.github.io/astropy.github.com/affiliated/index.html
Right now the only "other" package is astropysics... What other ones should we add?
cc @astrofrog @perrygreenfield
=> Add other pkgs

affiliated/registry.json
naima is a pure-Python package that allows to infer the properties of relativistic particle energy distributions from observed nonthermal spectra. It has two major components: a set of nonthermal radiative models (synchrotron, inverse Compton, bremsstrahlung, neutral pion decay), and a set of functions that use emcee to infer the particle distribution properties by fitting observed spectra through an MCMC procedure.
 - Documentation: http://naima.readthedocs.org
 - Code: http://github.com/zblz/naima
 - PyPI: https://pypi.python.org/pypi/naima
=> Add naima to affiliated registry

affiliated/registry.json
I'd like to have Omnifit added to the affiliated package registry, as I described earlier in  [the Google Groups thread](https://groups.google.com/forum/#!topic/astropy-dev/IotGX60E-OA) on the matter.
Omnifit is a package intended for the analysis of astronomical ice spectroscopy, with the special purpose of being able to easily compare data acquired in laboratories with spectra acquired using telescopes. An early version it is featured in my [PhD thesis](https://www.researchgate.net/publication/281458993_Mapping_of_Ice_and_Gas_on_1000_AU_scales), and a paper featuring it is also in final stages of preparation.
The website for Omnifit can be found at https://ricemunk.github.io/omnifit/
Let me know if you have any question or comments on this.
=> Added omnifit to affiliated registry

about.html
This PR updates the list of coordination committee members based on the changes proposed in https://groups.google.com/forum/#!topic/astropy-dev/A6g8n5RQL00 .  The companion change in the documentation is in astropy/astropy#4432
=> Updates to coordination committee membership

affiliated/registry.json
I would like to propose the MaLTPyNT code as an affiliated package.
This set of libraries and scripts was originally written with the timing properties of the NuSTAR X-ray mission in mind, but it is easily usable with event lists from other X-ray missions or light curves from any instrument.
It makes it possible to calculate light curves starting from event lists, power density spectra, cross spectra and derivatives, and time lags starting from event lists or lightcurves in FITS or text format, from X-ray datasets, and to simulate dead-time affected datasets.
The code is structured according to the Astropy template, and documented following most of the Astropy Guidelines. Astropy functions are used mostly for for FITS handling and time conversions. 
It is distributed through a bitbucket …
=> Add MaLTPyNT to affiliated registry

affiliated/registry.json
It makes no sense to list the link of the repos twice, so I've updated the ``home_url``s to point either to the webpage (if there is one), or to the docs page. In the odd cases there isn't any docs page yet, so then repo is left in place.
=> Updating links to point to the webpage or docs page

affiliated/registry.json
This PR modifies `affiliated/registry.json` to apply for affiliated-package status for Halotools.
=> Submit Halotools as a provisional affiliated package

help.html
This updates the "getting help" page to point people to the astropy gitter channel. Prompted by @cdeil's suggestion on astropy-dev.
Note that, at least for now, I am *not* removing the mention of the IRC channel as it still has occasional people there.  But it's at the bottom of the list so we can probably phase it out if gitter does indeed catch on this time. 
cc @cdeil @astrofrog
=> add mention of gitter in the getting help page

update_roles.py
Adding "Sébastien Fabbro" to the team requires Python 3.
=> Migrate roles update.py to Py3 (req'd for unicode names)

roles.txt, team.html
Per request from @eteq, I'm adding myself to the deputy slot for the Astropy web site role. Happy to be helping out!
=> Add Grant Tremblay to Astropy Website deputy role

roles.txt, team.html
Sébastien Fabbro has volunteered and committed to this role for at least a year.
=> Add Sébastien Fabbro as Gentoo packager

roles.txt, team.html
> I would like to volunteer for the unfilled role of deputy in astropy.io.misc.
> 
> I do a lot of I/O with Astropy Tables, in particular in HDF5 format, so I know well enough how it works (so that I can participate actively in the discussion when people submit PRs) and also some points where I would like to propose changes. 
> 
> Let me know if I can help with this, or feel free to suggest parts of the project where more help is needed. I use a lot the following subpackages: table, modeling, io.*, and sometimes coordinates, units, time, wcs.
> 
> I'm the principal maintainer of MaLTPyNT, a provisionally-accepted astropy-affiliated package (now being merged into github.com/stingraysoftware/stingray, for which we will ask for affiliation eventually), and the Sardinia Radio Telescope Single …
=> Add Matteo Bachetti in deputy io.misc role

roles.txt, team.html
> I will be glad to have a lead or deputy role for Arch Linux packaging.
> 
> Best,
> Miguel
=> Add Miguel de Vol-Borro in Arch linux role

roles.txt, team.html
Adds @bsipocz to the roles as a deputy release manager.
Also removes the footnote for @astrofrog (is that ok?  I can back out the commit if not, @astrofrog)
=> Add @bsipocz as releaser

roles.txt, team.html
This adds Tom Aldcroft as "process-only" lead and David Shupe as deputy with primary responsibility for technical review and development.
=> Update lead and deputy for astropy.constants

affiliated/registry.json
This PR updates the "glue" and "reproject" provisional affiliated packages to full affiliated package status.
The author of these packages (@astrofrog) requested a re-review, and the coordination committee (sans @astrofrog himself) agreed that both packages are sufficiently mature and meeting the affiliated package standards to be upgraded to full.
One item of discussion was the nature of `glue` as a non-astro-specific library.  There was some question whether that means it belongs as an affiliated package.  However, given its use in astronomy, the substantial (and continuing) effort @astrofrog has put into making it compatible with `astropy`, and the simple fact that the authors made the request, we concluded it is just fine.
=> update reproject and glue to full affiliated status

css/jquery.sidr.light.css
While working on #162 and #163 I noticed that when the sidebar appears with the menu (more importantly, it's what you see on a phone), you get this color:
That solid orange was very glaring and painful (at least on my monitor), so this PR changes it to match the gradient that the "buttons" on the rest of the page look like:
I think this is much more pleasant to look at.  This is quite subjective though, so it would be good to hear if others agree!
=> Make sidebar be the gradient instead of pure orange

index.html
This is the other thing I said I'd like to modify in #159 (https://github.com/astropy/astropy.github.com/pull/159#issuecomment-307214063), in addition to #163. It updates the front page to have "Documentation" use the fancy dropdown thing @abostroem made for the "About".  Looks like this:
@abostroem and @kelle ?
=> Add documentation dropdown

css/style.css, index.html
This is one of the things I said I'd like to modify in #159 (https://github.com/astropy/astropy.github.com/pull/159#issuecomment-307214063).  It updates the front page to include the current version in the "what's new" section, looking something like this:
I think this also actually addresses my "wall of text" concern in #159 now that I see it.  What do you think about this, @abostroem and @kelle?
=> make whats new centered and include current version

affiliated/registry.json
The old link is dead, and this seems to be the new one. Pinging the maintainer in case I'm wrong @RayPlante
=> Replace PyVO webpage link

announcements/release-2.0.html, index.html
This PR adds the release announcement for v2.0.
One semi-questionable item here: I've included the mention that this is the last 2.x-compatible version in the list of "New and improved major functionality".  It's not clear that it's literally that, but it seemed one of the best way to get people's attention - it's also mentioned in the bottom paragraph, but that's not as obvious as it seems like that should be.  But it could be put above, as well, if even more prominence is desired.
You can see this rendered at http://eteq.github.io/astropy.github.com/announcements/release-2.0.html
=> added release announcement for 2.0

affiliated/registry.json
The provisionally accepted MaLTPyNT was renamed to HENDRICS and the API is now based on Stingray.
=> Maltpynt is now HENDRICS

affiliated/registry.json
This should be looked at by @astrofrog because of the second commit, which removes WCSAxes. 
That may not be the way to handle packages that have migrated into core, but I was looking at the json anyway and figured I'd raise the issue. Happy to revert if desired....
=> A little cleanup of affiliated package json

affiliated/registry.json
This PR makes two changes:
+ Update some details of affiliated package entries that were generated while working on the numfocus affiliated package blog post this past summer.
+ Adds two new keys to the json entries: `image` and `educational_materials_link`
I can separate this into two PRs if you would like.
=> Update affiliated package repo with information gathered over summer

update_roles.py
Per discussion at the coordinators meeting today, we want to add a reminder that any update to roles needs to be reflected in the `astropy-core-maintainers` google group.  This list is now meant to include all those who have a role on the team page.
=> Add reminder about updating astropy-core-maintainers group

affiliated/registry.json
I tried reading the `registry.json` file with `astropy.table`, and it fails because HENDRICS doesn't contain an `image` tag.
=> Add null "image" for HENDRICS

affiliated/registry.json
I copied the short descriptions for the packages into the affiliated package registry. 
cc @astrofrog @jobovy
=> Add short descriptions for glue, gala, galpy

contribute.html, help.html
This replaces gitter by slack on the website. Just to explain the motivation for the change in wording, I feel like previously we made it seem too much like people would actually get an immediate reply, but I think we want to make it very clear this is not the case and that people shouldn't get frustrated if we don't reply immediately (when people use IM services they have waaaaay less patience than email lists). I'm open to suggestions though.
=> Mention slack on website

affiliated/registry.json
Stingray is a Python API for spectral-timing analysis of X-ray and multi-wavelength data. 
stingraysoftware.github.io
github.com/stingraysoftware/stingray
=> Add stingray to affiliated packages?

affiliated/registry.json
I'd like to deregister montage-wrapper as an affiliated package as I no longer have time to maintain it and I think as a project we should invest into the reproject package instead.
I also plan to move the repo back from the astropy organization back to my user repo. Sounds ok? I'll then add a note to say it's no longer maintained.
=> Remove montage-wrapper

affiliated/index.html
I know this page will need to be updated in future but this is just a temporary change to avoid confusion.
=> Remove mention of provisional affiliated packages

acknowledging.html, announcements/release-3.0.html, index.html, team.html
This PR adds text for the release announcement for Astropy v3.0.
One thing to note: The "cite this" part is slightly awkward given paper ii is not yet in the journal.  I basically adopted @bsipocz's approach from astropy/astropy#7158, although modified to fit the html.  There is an open question whether we should update the web site's citation text (http://www.astropy.org/acknowledging.html) to *also* say this.  I'm inclined to wait on that until the paper is actually in the journal.  If we agree on this I'll just make a WIP PR to do that separate from this one.  Any opinions on this, @adrn, @crawfordsm, @hamogu, or @bsipocz?
=> Add 3.0 release announcement

index.html
Fix #186.
This is a quick fix until doc overhaul mentioned in https://github.com/astropy/astropy.github.com/issues/186#issuecomment-363866777 .
Original motivation: I was looking for 2.x doc and couldn't find it, so I went to this drop-down menu and couldn't find it either.
=> Remove old doc links. Add 2.0.4 doc link.

.gitignore, affiliated/index.html, css/style.css, js/functions.js
Partially in the spirit of astropy/astropy-APES#40, @eteq (LONG ago) proposed an overhaul / refresh of the Affiliated Packages table. 
Following on #pyastro18's recent Hack Day, @eteq, @astrofrog and myself propose the following design. Note that this specific design is entirely the brainchild of @astrofrog, and @eteq did most of the actual implementation. 
This new table aims to simultaneously increase per-package information density while also improving readability. Miraculously, I think it does both (thanks entirely to @astrofrog and @eteq's great ideas). 
This table, of course, dynamically pulls from the JSON registry, and can be easily adapted to any forthcoming evolution of the Astropy affiliated package model. 
Edit: You can see a live preview of this change …
=> A new design for the Affiliated Packages Table

css/style.css, index.html
Fixes #105 
Added a footer on home page, combining Astropy Code of Conduct and NumFOCUS stamp.
Preview:
The layout is adaptive for a good range of browser screen width. One way to see the changes _locally_ would be as follows:
1) Clone my repo from [https://github.com/apooravc/astropy.github.com](https://github.com/apooravc/astropy.github.com)
2) After cloning, only the master branch would be available locally. Enter `git checkout -b add-footer origin/add-footer` to get the branch _add-footer_ locally.
3) The changes could then be seen on home page.
@astrofrog @kelle @eteq Please have a look.
=> Fix #105: Place the NumFOCUS digital stamp on astropy home page

index.html
Hello! I just wanted to get started with AstroPy and spotted a dead link in the installation part of the main page.
=> Fix Anaconda URL on the main page

css/style.css
Fixes #250 
Adjusted padding by adding a new CSS selector to remove extra spacing in Roles table of team page.
@eteq @astrofrog Please have a look.
=> Fix #250: Vertical spacing in team page

affiliated/index.html
This reworks the section on installing affiliated packages to be a bit more direct for users.  For instance the first Astropy Conda channel link they encounter is the actual channel, not the Github repo.
It also replaces href tags like "here" or "end of this page" or "below" with more descriptive text.
=> Improve instructions for installing affiliated packages

affiliated/index.html
Now that the main workflow for proposing affiliated packages has been finalized, this updates the website to point to these new guidelines. As usual, you can use the 'giles' link below in the status checks to see the rendered version.
=> Updated instructions for proposing affiliated packages

css/style.css, js/functions.js
I found the current rate of drawing horizontal rules ("every 4th row") to be visually confusing. This instead draws one at the top of each block of roles.
Fixes #282
=> Change when horizontal rules are drawn

about.html, acknowledging.html, affiliated/index.html, announcements/release-3.1.html, code_of_conduct.html, contribute.html, help.html, index.html, team.html
Just what it says on the tin... To be merged when the 3.1 builds are all done.
=> Release announcement/update for 3.1

index.html
This addresses #293: if users installed conda with miniconda, they may need to `conda install astropy`.
=> Add a conda install example to landing page

affiliated/index.html
This section is quite outdated: The described software is no longer developed or maintained, and does not work with Python 3. Referring to that software may be misleading for new users. 
Therefore, it should be removed.
Fixes #304.
=> Remove subsection "Other astronomy packages"

contribute.html, index.html
Spurred on by astropy/astropy#8512 (which updated the existing button to the new NF donate site), I realized that we still only have a donate button in the core package readme.  This PR adds donate buttons to the front and "contribute" pages on the web site.  It therefore closes #168.
cc @astrofrog @kelle
=> Add donate buttons to web site

affiliated/registry.json
Python-cpl was one of the first affiliated packages. My intention to have it there was that it could serve as a start for other pipeline/data reduction framework integration modules.
This however never happened and seems to be not happen in the near future, and I have neither time nor competence to develop/push one myself. And compared to the others, it is rather trivial now.
Also, the glue to astropy is rather loose; it mainly converts the input and output files with `astropy.io.fits` into objects.
Maybe it is better to unlist it now. If at some point there is a need for a common processing framework, we may bring it back, maybe in a modified form.
The [package](https://github.com/olebole/python-cpl) ofcourse continues to exist and will be maintained ;-)
=> Remove python-cpl from list of affiliated packages

about.html, acknowledging.html, affiliated/index.html, code_of_conduct.html, contribute.html, css/style.css, help.html, index.html, js/functions.js, team.html
Fixes #77 (for about page only at the moment)
Since this is from a branch on my fork, I can't generate a preview on Github pages, as it's allowed from the master branch only. One way to see the changes _locally_ would be as follows:
1) Clone my repo from [https://github.com/apooravc/astropy.github.com](https://github.com/apooravc/astropy.github.com)
2) After cloning, only the master branch would be available locally. Enter `git checkout -b add-section-link origin/add-section-link` to get the branch _add-section-link_ locally.
3) The changes could then be seen on the about page.
@astrofrog @eteq Please have a look.
=> Fix #77: Make it easy to get links to sections

roles.json
Adds @mirca as GSoC deputy, and remove @taldcroft (as he was there for the transition from last year).
cc @bsipocz
=> Update GSoC deputies

affiliated/registry.json
This PR changes the Gammapy maintainer contact name for the https://www.astropy.org/affiliated/ page to @adonath and @registerrier . They have/are taking over as lead developers and maintainers for Gammapy. See https://gammapy.org/team.html
(I will leave astronomy in December, to work as data scientist in industry, so I'm handing off maintainer roles, starting with Gammapy.)
=> Change Gammapy maintainer to Axel & Regis

affiliated/registry.json
I propose to update the dev status for astroML. The package is stable as is, and we are also working on new functionality. 
First I though about the "Heavy development" version, but that is being used mostly for alpha versioned packages, while here two books are out with example usage of the package. The API is expected to stay backward compatible, if not it's only because of making it more in line with scikit-learn.
Bottom line, the package is not in "low activity" mode.
I was also on the verge of asking for the status to be changed for the testing, but such as we don't have one number (e.g coverage) to point to, and many of our testing are not (yet) in public CI (examples in the book manuscript, figure generations, etc.)
As for making it more astropy units aware, it's on my list.
=> Updating astroML dev status

affiliated/registry.json
Johannes left astronomy a year ago, and I will shortly.
@larrybradley and @keflavich agreed on the Astropy slack #regions channel to take over as maintainers. This PR implements that change for https://www.astropy.org/affiliated/index.html, they already have been co-maintaining the package and have permissions on PyPI.
@eteq - Could you please discuss this with the Astropy coordinators (if needed, since this is a coordinated package), and approve this PR or make a different suggestion?
=> Change regions affiliated package maintainers

roles.json
As discussed in the 2018 coordination meeting (and finally acting upon now...), this PR collapses the long list of "distribution" roles into a single line.
Some confirmation from others might be good that this is *actually* what was intended - I'm not 100% sure this is what we really meant based on the coordination meeting notes ... The exact line in the notes was "Remove Distribution subroles (need some phrasing)"
=> collapse distribution role into one section

js/functions.js, roles.json, validate_roles.py
This finally re-organizes the JSON file for the roles to be easier to read and update, in particular in relation to sub-roles. This makes the associated JS code simpler (in my opinion).
I've also removed @hamogu from the distribution role (it was for MacPorts) following his response in the roles survey, and fixed a missing description for the GSoC role that caused it to be absent from the roles descriptions.
[Preview](https://341-2081290-gh.circle-artifacts.com/0/html/team.html)
Fixes https://github.com/astropy/astropy.github.com/issues/326
=> Clean up roles JSON

roles.json
This PR is to add @Cadair as an astropy-helpers deputy maintainer - in fact this is to maintain extension-helpers, which I think we can consider part of the same role for now.
=> Add @Cadair as astropy-helpers deputy maintainer

affiliated/registry.json, roles.json
@cdeil, as requested, this removes you from the maintainer list for regions and astropy-healpix. Thanks for all the work you've put in to those package! :clap: :pray: :+1: Just for info, I'll remove you from the core-maintainers mailing list, and from the write-access teams for those packages.
@larrybradley @keflavich - I'd already switched to to maintainers in the affiliated package package but I'd forgotten to update the role. I've put you both under 'lead' since we're going to get rid of the lead/deputy distinction anyway.
=> Updated maintainers for regions and astropy-healpix

affiliated/registry.json
This package is a Pythonic reincarnation of Jennifer Lotz's IDL code for calculating non-parametric morphological diagnostics of galaxy images, such as the Gini-M20 (Lotz et al. 2004), concentration-asymmetry-smoothness (Conselice 2003), and multimode-intensity-deviation (Freeman et al. 2013) statistics. In addition, the code is quite good at fitting single-component 2D Sérsic profiles, a functionality powered by Astropy's modeling & fitting module. Finally, statmorph makes heavy use of the photutils affiliated package, so I think it would blend nicely with the rest of the Astropy ecosystem.
=> Proposed affiliated package: statmorph

affiliated/registry.json
mocpy's docs to have been updated to use the github pages URL instead of an RTD url.  This just updates that to get the CI back and working for this repo.
@bmatthieu3 can probably confirm that this is the right URL - please approve or :+1: if you agree with this
=> Update mocpy web site

affiliated/registry.json
Org was moved back at IVOA Interops 2019
=> Fix repo link for pyvo

roles.json
Since I am going to have less time to spend on the project over the coming year, I want to step down (or scale back) some of my roles in the project so that I can focus better on my remaining roles. In detail, I am:
* Stepping down as Slack moderator
* Stepping down as a conference coordinator
* Stepping down as astropy-helpers maintainer - that package is in bugfix maintenance mode anyway, so it shouldn't matter much - but I won't be able to be responsible for fixing things at short notice if anything breaks due to upstream changes in sphinx, pytest, or python, so I'm not the right person to keep an eye on or lead this
* Stepping down as astropy.io.misc maintainer - I'm not familiar with most of the sub-package anymore, so I'm not the right person to lead this
* Stepping down as …
=> Update roles for @astrofrog

roles.json
This PR adds @eslavich as one of the `io.misc` deputy maintainers.  @eslavich is a prime `asdf` maintainer, so he would be focusing in `io.misc.asdf`.
=> add eslavich to io.misc role

roles.json
This adds the affiliated package editorial role to the list of roles
cc @hamogu @pllim (can't assign you for review due to team permissions for now but clearly we will need to add permissions for you for this repo)
=> Added affiliated package editorial role

css/style.css, index.html
This adds an acknowledgement and statement about recent events that have taken place in the US as a banner to the astropy.org front page. The positioning is currently a bit messed up: It works if I put this after the "whatsnew" section, but the large `margin-top` setting on whatsnew squishes it upwards if I try to put it above the whatsnew, e.g.
=> Add statement about recent events

affiliated/registry.json
lenstronomy is a multi-purpose gravitational lensing and image modeling package. lenstronomy finds its use e.g. in modeling gravitational lenses for time-delay cosmography (measuring the Hubble constant), substructure lensing, galaxy morphology analysis and quasar host decompositions. The package was originally presented in Birrer & Amara 2018 and the core module ,linear basis sets for (lensed) surface brightness decomposition, is presented in Birrer et al. 2015.
=> update registry with lenstronomy entry

contribute.html, help.html
Added bit about how we use astropy-dev to discuss governance to both the Get Help page and the Contribute page. Also polished the text on other bullets to tighten it up a bit.
=> adds role of astropy-dev in governance.

roles.json
@bsipocz @pllim - I've added you both to both the testing and documentation infrastructure roles.
The roles page was out of date since @bsipocz already had write access to the sphinx infrastructure (as it should be), but I've now added @bsipocz to the pytest plugin team and @pllim I've added you to both. This PR then reflects the current write access. Sorry that it took so long to do this!
@embray FYI I've also added you to the teams for the pytest and sphinx plugins to facilitate your new role!
=> Added @pllim and @bsipocz to infrastructure roles

contribute.html
The primary change is adding a section about justifying the time for contributing to Astropy in an academic setting.
Along the way I noticed that the first two sub-sections were `<h1>` when they really should be `<h2>` to fit in with the rest.  I also saw that the `href` for the Donate section seems wrong.
=> Add subsection to Contribute page about justifying effort

acknowledging.html
This updates the bibtex record for the Astropy 2018 paper to the ADS record that correctly puts "Astropy Collaboration" as the first author. The original record in ADS had me as first author, but later fixed the record, so we should update it here too!
=> Use updated ADS bibtex record for Astropy 2018 paper

roles.json
As discussed by email with @eteq (since these roles are well populated)
=> Remove @eteq from docs and testing infrastructure roles

index.html
While this banner was added at the peak of the events earlier this year, it might be time to remove this banner and perhaps replace it with a more general statement such as the one suggested here
=> Remove banner

roles.json
I'd like to suggest we move ahead with creating a 'DevOps' role that would initially be populated with @embray, @pllim and @bsipocz. I've therefore added such a role to the list here, but **mainly with placeholder information**. I'm not thrilled about the current role title, and the list of responsibilities is just a placeholder.
This role would be a significant one as it would come with admin access to all repositories in the org to enable some of the responsibilities I've listed (although we could investigate whether maintainer access is sufficient - basically whatever level is needed to make it possible to do the things).
At this point, what I'd like is for @embray @pllim @bsipocz to take a look at this and make concrete suggestions on what you'd like the role title and …
=> Add new DevOps role

index.html, team.html
This updates the current version to version 4.1 as well as the contributor list update (I'll do a follow-on PR with the announcement once the conda builds are ready)
=> Update for release 4.1

affiliated/registry.json
I recently got access to the name "gala", bringing the pypi name and the github repo name in line, so I will be using this name going forward (🎉).
=> Change gala pypi name

contribute.html
This adds a new section which describes assuming a formal Astropy Role as a way to contribute to Astropy.
=> Add section to Contribute page for Astropy role

contribute.html
Thinking of #416 as the "straw that broke the camel's back", I noticed while reviewing a few consistency issues and recognized that the page has gotten big enough that it could use a sort of table of contents.  So this PR does a general cleanup of the contribute page and adds some quick links to the top.
(You can see it live at http://eteq.github.io/astropy.github.com/contribute.html at the time of this writing)
=> Contribute page cleanup & ToC

roles.json
Following a discussion on Slack about the topic (cc @bsipocz @keflavich @kelle), this PR removes the implicit "slot" on the finance committee for the ombudsperson.
The gist of the justification is that, while the original motivation was that the ombudsperson should be there to be aware of conflict-of-interest, etc issues, some felt it seems odd/problematic in appearance that someone who's supposed to take an arbitrator role is involved in a decision-making body. (I'm not saying who "some" is since I'm not entirely sure who if anyone in the Slack thread actually thought this vs was concerned about the appearance, but if anyone wants to they are welcome to add further details!).  So this change removes that expectation.
Note that this is *not* necessarily meant to say there shouldn't be a …
=> remove ombuds slot from finance committee

affiliated/registry.json, roles.json
Fix #410 by 
* Removing Seifert from all active roles, as he requested
* Removing Crawford from specutils but keep him in ccdproc, as Matt Craig requested
There is a larger issue of general upkeep of the whole list (https://github.com/astropy/astropy.github.com/issues/410#issuecomment-716564801) but that is out of scope here and not the intent of the original issue I opened.
=> MNT: Remove Seifert from roles, remove Crawford from specutils

acknowledging.html
The BibTeX generated by the big orange button at https://www.astropy.org/acknowledging.html currently doesn't work, because all the `\`s are swallowed by Javascript. This escapes them, so they aren't.
=> Escape `\`s in BibTeX

roles.json
@lpsinger is the biggest contributor to astropy-healpix at the moment and familiar with the astropy workflow/guidelines - he has indicated that he is happy to co-maintain astropy-healpix.
=> Add Leo Singer to astropy-healpix maintainers

team.html
This PR updates the list of voting members to reflect the results of the initial voting members election.
cc @ceb8 @mwcraig @Cadair
=> update voting members following Jul 2021 election

roles.json
- I no longer have time to help with conference coordination
- I haven't worked on package template maintenance in too long, and won't have time to re-engage, so removing myself from that role as well.
- I added Jonathan Sick (@jonathansick) because he has been hired to work on infrastructure for the astropy tutorials.
=> Remove Adrian from roles, add Jonathan Sick to tutorials infrastructure team

affiliated/index.html
just what it says on the tin... just a couple of out-of-date links.
=> fix links to point to newer versions of affiliate instructions

about.html
That page says “This page has been removed. For an overview, see the
http://www.astropy.org page”, and has done since at least v2.0.16
(https://docs.astropy.org/en/v2.0.16/overview.html).
=> Remove link to “documentation overview”

roles.json
Based on nominations from the community, the Coco has reached out to Derek to
nominate him as affilated package editor to replace Moritz, who wants to step
back from other astropy roles to make time for Coco work.
=> Make Derek affiliated package editor

roles.json
Moritz has said in this nomination for the Coco, that he would step back
from other Astropy roles if elected. Based on nominations from the community,
the Coco has contacted Aarya, who is interested in joining the finance
committee.
This PR will stay open for two weeks for any discussion.
=> Replace Moritz with Aarya on the finance committee

roles.json
Please add William Jamieson as a maintainer of `astropy.modeling`.
William has been working on modeling for the last several months with some substantial contributions. He is also addressing issues raised by users on github and is willing to continue in a maintainer role and provide support and guidance. I believe he is fully qualified for this role.
=> Add William Jamieson as a modeling maintainer

roles.json
The CoCo recently discussed a proposed restructure of the Learn Astropy roles and approved the following:
Consolidate Learn Coordinator, Tutorials and Guides, and Workshop Coordinator Roles into sub-roles under Learn:
**Learn**
- Coordinators - Lia Corrales, Kelle Cruz, Adrian PW, Matt Craig
- Infrastructure - Adrian Price-Whelan, Erik Tollerud, Jonathan Sick
- Content Editors - Lia Corrales, Kelle Cruz, Matt Craig, Adrian PW
- Workshop Coordinators - David Shupe, Brett Morris, Kelle Cruz
I have modified the roles.json file to reflect this change.
=> Restructure of Learn Astropy roles

affiliated/registry.json
With RiceMunk/omnifit#43 this package is now fully supporting Python 3.7-3.10 pip-installs and passing all tests against Astropy 5.0. I have also upgraded the `testing` level to `Good`, since there are CI tests for Linux, macOS and Windows with coverage of 85-100% (with the exception of `utils`).
=> Update Omnifit package status

team.html
The previous wording only asked for volunteers for currenty unfilled roles, but there are many roles where additional help would be useful, even if they are not currently unfilled.
=> Invite applications or nomination for all roles

index.html
This uses JS code adapted from
https://github.com/sunpy/sunpy-sphinx-theme/blob/main/sunpy_sphinx_theme/sunpy/static/version.js
to get the latest version from PyPI which will save having to update it during releases. This is an alternative to https://github.com/astropy/astropy.github.com/pull/406 and the advantage here is we maintain the same formatting as before.
@Cadair - do you want us to include the sunpy license or is this trivial enough to life without attribution? (either way is fine!)
=> Show latest core package version from PyPI

roles.json
@saimn @embray @bsipocz - could you check over the responsibilities and suggest changes/additions? The bottom line is I think the responsibility of the team should be the core package releases and then oversight of the release process for other organization packages (but not necessarily doing those releases)
=> Update release coordinator to release team and update membership

affiliated/registry.json
Kanon is a package for modeling ancient astronomical models from tables and mathematical models. It uses astropy for interoperability with modern astronomy tools.
It is a really specialized package but an interesting addition.
=> Add kanon to affiliated packages

roles.json
This has been discussed in the dev telecon 2022-02-03 and there was general agreement to add such a role. This PR is a draft of that role description; unfortunately I don't remember exactly how we described this role in the telecon, so this is based on my notes, my recollection and the discussion in https://github.com/astropy/astropy-project/issues/136
@bsipocz You had a very good description of this role in the last dev telecon, but I was not fast enough to write that down. Could you please have a look at this and comment or suggest changes to include what you said?
x-ref: https://github.com/astropy/astropy-project/issues/136
=> Add general maintainers role for astropy core package

roles.json
While looking at #486 I realized we should probably explicitly note which roles are detailed in APE0.  So this PR does exactly that, adding a couple of links back to APE0 for the Coco and the ombudsperson (the voting members are already linked to APE0.)
=> Updating roles to add APE0 links when relevant

affiliated/registry.json
<hr/>
Following the [discussion](https://docs.google.com/document/d/15JSFh3OMF9Iz6ov3q_xxGO_BL8hRnuse4IMUrqEIvcg/edit#bookmark=id.smndathb9rse) at today's Astropy dev telecon, it was decided that `asdf-astropy` should be made a coordinated package given that the functionality provided by `astropy.io.misc.asdf` is being moved from the astropy core to this package.
Tagging @pllim and @dhomeier
=> Add asdf-astropy as a coordinated package

about.html, acknowledging.html, affiliated/index.html, announcements/release-2.0.html, announcements/release-3.0.html, announcements/release-3.1.html, announcements/release-3.2.html, announcements/release-4.0.html, announcements/release-4.1.html, announcements/release-4.3.html, announcements/release-5.0.html, code_of_conduct.html, contribute.html, credits.html, help.html, history.html, index.html
This pull request adds a (relatively) brief history of the astropy project to the website.
Feedback on this would be very helpful. While an attempt has been made to include major events in the history of astropy, and to acknowledge the breadth of contributions to the project, there well may be unintentional omissions. This draft includes text written by a few different people, so there may be abrupt changes in tone or style.
=> Add history of project to website

affiliated/registry.json
Following discussion at today's Astropy coordination meeting, there was consensus (i.e., no objections) to add specreduce as a coordinated package given that it is referenced in the already-accepted [APE13](https://zenodo.org/record/1117943) and there's now a public release.
(Still needs CoCo approval, and @tepickering's :+1: to be listed as a maintainer)
=> Add specreduce as a coordinated package

roles.json
The Coco discussed developer telecons and decided to add a new role to
the teams page to
(a) give a point of contact for poeple who want to join the telecons, but
for some reasons have individual questions and
(b) ensure that role is not forgotten and appropriate efforts are made
fill it, should the current people in this role stop
doing it for any reason.
Note: By time effort, this is probably one of the smallest roles on the list
but this list is not a credit page - it's just a list
of tasks and people.
CC: @mwcraig
=> Add a new role for dev telecons

team.html
Adding Eero and Ricky, as elected in the July election.
=> Add new voting members elected in July 2022 election

roles.json
These are roles that I either will not have time to do in the next year, or haven't been doing effectively.
=> Remove APW from two roles

roles.json
I noticed that `asdf-astropy` is not listed on the https://www.astropy.org/team.html page under the `Coordinated package maintainer` heading, but it is listed under `Coordinated Packages` on https://www.astropy.org/affiliated/index.html. This PR resolves this difference.
=> Add asdf-astropy to main team page

roles.json
Prompted by astropy/astropy-project#322 - clarify that domain name work lives in the web page maintainer role
=> add role of the domain name to the web page maintainers

roles.json
Clara has indicated by email that she's currently too involved in teaching and getting her PhD done to fill this role. We'd love to have her back, but life happens and the purpose of the roles list is to record who does what right now and whom to contact for anything that comes up related to a specific role. Thus, this PR to remove her from the role, with the understanding that we are happy to add her back in as soon as she has time again.
@ceb8
=> Remove Clara from Dev telecon organizer

roles.json
We no longer maintain ci-helpers and astropy-helpers.
* [ci-helpers](https://github.com/astropy/ci-helpers) became defunct after we moved away from Travis CI and Appveyor. Only `pip_pinnings.txt` is kinda used (but not really because it is empty file right now).
* [astropy-helpers](https://github.com/astropy/astropy-helpers) became defunct after [APE 17](https://github.com/astropy/astropy-APEs/blob/main/APE17.rst) was accepted. It is already archived.
Affected people in the removed listings:
* @Cadair 
* @bsipocz 
* @eteq
=> Roles: ci-helpers and astropy-helpers are no more

roles.json
`specreduce` is listed as Coordinated under https://www.astropy.org/affiliated/index.html#coordinated-package-list but not listed in `roles.json`. Here, I simply copy over the "Maintainer(s)" listed over there to this JSON file. Whether they are really actively maintaining or not, I do not know. If this listing is no longer accurate, please tell me the current maintainers for `specreduce`. Thanks!
Affected people in the added listing:
* @tepickering
* @eteq
=> Roles: Add specreduce to Coordinated section

roles.json
Astropy has not been active for several years now. And even if it becomes active again, it would be under OpenAstronomy. For instance, see https://openastronomy.org/gsoc/gsoc2023/#/mentors for GSoC 2023.
Or do you think we should keep the role but link directly to OpenAstronomy page? I don't see a "roles" page that that is not by year. Maybe I missed it?
Affected people in the removed listings:
* @bsipocz 
* @eteq 
* @mirca
=> Roles: GSoC under OpenAstronomy now

roles.json
This PR is me removing myself from this role - in practice I do not use Facebook anymore so I cannot be effective in this role (although I still occasionally can pop in to leave comments when pinged).
cc @pllim who reminded me I can do this myself after I said it in the roles survey :wink:
=> Removing myself from Facebook community role

roles.json
Adding @olebole in this role with write access in astropy/astropy, in response to https://github.com/astropy/astropy-project/issues/327#issuecomment-1557532580 .
=> Add Ole Streicher as general maintainer for the Astropy core package

affiliated/registry.json
Adds @braingram as a maintainer for `asdf-astropy`.
=> Add Brett Graham as maintainer for asdf-astropy

affiliated/registry.json
regularizePSF is a new tool made as part of [the PUNCH mission](https://punch.space.swri.edu/) to correct variable point-spread functions in images. It is applicable to any astronomical image with a variable PSF. It includes tools to model the variable PSF, regularize the PSF, and visualize results/intermediate steps. The PUNCH Science Operations Center team thinks it would be a good addition to the astropy affiliated package list.
=> Proposed affiliated package: regularizePSF

roles.json
This one might want to wait for when we officially retire the template in favor of OpenAstronomy, or should we go ahead?
* https://github.com/astropy/package-template/issues/519
Affected people in the removed listing:
* @larrybradley
* @Cadair 
* @astrofrog 
* @bsipocz
=> Roles: Remove package template

index.html
This updates the front page installation instructions:
* No longer recommend the Anaconda Python Distribution as being the best way - as in our main install instructions, pip should be first.
* Include ``--upgrade`` flag for pip because might as well to ensure the latest version (mentioned in https://github.com/astropy/astropy/issues/15487)
* Include ``[recommended]`` for pip since, well, it is recommended!
* Use conda-forge for conda due to https://github.com/astropy/astropy/issues/15122 - even though right now defaults is up to date again, it might not be in future. Conda-forge will always be more likely to be up-to-date.
I think it's important to fix this as these are our most visible user-facing installation instructions.
=> Updated installation instructions

roles.json
@kecnry and @cshanahan1 already have maintainer access to `specreduce` for a while as individuals and they are actively maintaining the package. I have taken the liberty to clean up `specreduce` and `specreduce-data` permissions by doing the following and this PR just making their existing jobs official.
* Remove individuals with only Read access to `specreduce`. This is unnecessary because it is a public repo. If you want them to have access for triage, create a proper triage team. Refrain from providing arbitrary individual access.
* Added Kyle and Clare to https://github.com/orgs/astropy/teams/specreduce-maintainers and downgrade that team's access from Admin to Maintain.
* Created a new admin team with existing admins (@eteq and @tepickering) and give them back their existing access …
=> specreduce: Add Kyle and Clare as maintainers because they already are

team.html
The Astropy Collaboration was awarded an IOP Publishing "Top Cited Paper - North America" for having a paper in the top 1% of cited papers for 2020–2022.
=> Added link to IOP Publishing "top cited paper" award 

roles.json
As discussed and agreed upon at Astropy Coordination Meeting 2023 (myself, @eteq, @hamogu, @weaverba137, @aaryapatil, @saimn), Finance Committee shall be moved up to after Ombudsperson. This is because given that the committee now oversees multiple grants for the Project and so on, that would be a logical (and hopefully uncontroversial) place to put it.
Affected people (the Finance Committee):
* @kelle 
* @aaryapatil
* @jdswinbank 
* @eteq 
Out of scope: Re-ordering of all other roles.
This is part of #519
=> Roles: Move Finance Committee to after Ombudsperson

.circleci/config.yml
This pull request is to remove defunct setup. I think I did the UI thing as documented in https://github.com/cadair/giles#circleci-artifact-links . We will see...
Fix #566
cc @Cadair
=> MNT: Remove defunct CircleCI setting

about.html, acknowledging.html, affiliated/index.html, announcements/release-3.1.html, announcements/release-3.2.html, announcements/release-4.0.html, announcements/release-4.1.html, announcements/release-4.3.html, announcements/release-5.0.html, announcements/release-5.1.html, announcements/release-5.2.html, announcements/release-5.3.html, announcements/release-6.0.html, code_of_conduct.html, contribute.html, credits.html, help.html, history.html, index.html, team.html
Fix https://github.com/astropy/astropy.github.com/issues/565
As per https://github.com/astropy/astropy-APEs/blob/main/APE21.rst
=> Remove mention of LTS in navbar

affiliated/registry.json, roles.json
I am stepping down from several of my rolls with the Astropy project. This is because I am moving away from working at STScI to working for a private company. Due to this change my time and ability to contribute to astropy will be much more limited. For now I believe that I can continue to act as an `astropy.modeling` maintainer as a volunteer in my personal time.
=> William Jamieson is stepping down from several roles

roles.json
Following up on his own offer the Coco is nominating Hans-Moritz Günther as Affiliated Package editor to replace William, who is stepping down from this role (#576).
@hamogu has served in this role until the end of 2021; note that in the future both editors will work in a re-defined function under our partnership with the pyOpenSci review system as described in #574.
Pinging @ceb8
=> Nominate Moritz Affiliated Editor

roles.json
Part of the transition of our Affiliated Package Review process into [partnership with pyOpenSci](https://pyopensci.discourse.group/t/astropy-partnership-next-steps/432/6)
Fixing #569
=> Update Affiliated Editors' role descriptions to include their future tasks under the pyOpenSci partnership

affiliated/registry.json
To reflect reality. Accompanying task is to update the github team and revise the accesses to the repo (as it's currently a mixed of individuals rather than team-based)
cc @pllim
=> DOC: updating pyvo maintainer list

roles.json, team.html
Adding a link from the Roles page to the astropy policies document in the astropy-project repo, per https://github.com/astropy/astropy-project/pull/400.
The edit to `roles.json` is unrelated, I just noticed that the link to the CoCo operating policies was dead, and discovered there was an errant space in the url.
=> Adding link to astropy policies document

about.html, acknowledging.html, affiliated/index.html, announcements/release-2.0.html, announcements/release-3.0.html, announcements/release-3.1.html, announcements/release-3.2.html, announcements/release-4.0.html, announcements/release-4.1.html, announcements/release-4.3.html, announcements/release-5.0.html, announcements/release-5.1.html, announcements/release-5.2.html, announcements/release-5.3.html, announcements/release-6.0.html, code_of_conduct.html, contribute.html, credits.html, help.html, history.html, index.html
Replace devdocs with direct RTD URL for developement docs.
HTTP is not secure and HTTPS for "devdocs" does not work.
=> Replace devdocs with direct RTD URL

roles.json
In the past several releases (and we only do a release every 6 months, so it's been a while), only @astrofrog and @saimn are alternating, so based on that, I am updating the Release Team membership.
Affected people in this listing:
* @embray 
* @bsipocz 
And, I have to confess that I accidentally already updated the actual "Astropy Project Release Team" GitHub membership. I thought this was already done over here but I must have imagined it. So, if this PR ends up changing, I'll update on GitHub side accordingly. I take full responsibility for this mistake and I apologize for any inconvenience caused.
=> Roles: Update release team members

roles.json
Madison has not been active for a while since the SOSS position lapsed and has not responded to developer surveys that we sent out. So I don't think this needs any 2-week periods nor debate? They are already listed under Lifetime Contributors (https://www.astropy.org/credits.html) for their extensive contributions prior.
=> Roles: Remove Madison Bray from DevOps

roles.json
In practice, Moritz has been hosting all the dev telecons lately. So I hereby propose we remove @nstarman from this role for now.
=> Remove Nathaniel Starman from dev telecon role

roles.json
Removing Nick from the `specutils` maintainers list after speaking with him on Slack about it.
=> Roles: update specutils maintainers

roles.json
@pllim pinged me to review roles in https://github.com/astropy/astropy.github.com/issues/519.  This PR removes @bsipocz as a `photutils` maintainer because she has not been active in that role in several years.
=> Roles: update photutils maintainers

roles.json
This PR removes my name from the `coordinates` and `utils` maintainer roles.
Neither of these are due to a lack of desire, but a lack of time.  I have not been able to keep up with these as finance and CoCo workload has taken over, so I need to step down.  Honestly I probably should have done this years ago.
I might try to ramp up again when my CoCo term expires, but time will tell :shrug: .
=> Remove me from coordinates and utils maintainer role

affiliated/index.html
Looks like in https://raw.githubusercontent.com/pyOpenSci/pyopensci.github.io/main/_data/packages.yml they changed
```yaml
partners:
- 'astropy'
```
to
```yaml
partners:
- 'astropy: link-coming soon-to standards'
```
that caused our parser to fail and result in empty listing. I was expecting one or two packages. This is a follow-up of https://github.com/astropy/astropy.github.com/pull/590 .
xref https://github.com/pyOpenSci/pyosMeta/issues/186
cc @dhomeier and @hamogu
=> APE 22 listing: Adjust to upstream YAML changes

affiliated/index.html
In the second post-APE 22 accepted package, we already run into problem that is related to https://github.com/pyOpenSci/pyopensci.github.io/issues/390 because https://github.com/kyleaoman/martini is published on PyPI as a different name https://pypi.org/project/astromartini/ while `martini` on PyPI is a completely separate package. Rather than trying to track this ourselves here, better to just disable PyPI field for now until this is fixed upstream.
=> APE 22 listing: Unsafe to assume PyPI name is the same as package name always

roles.json
@eslavich was added for `astropy.io.misc.asdf` but he should be removed now because:
1. `astropy.io.misc.asdf` is now `asdf-astropy` coordinated package with separate listing.
2. He no longer works at STScI who was paying him for this role.
3. He has not been active in the Project and did not respond to developer surveys.
xref https://github.com/astropy/astropy.github.com/issues/519
=> Roles: Remove Ed Slavich from io.misc

css/style.css, js/functions.js
Weird to have sub-role suddenly be bold font, and thus overshadowing other roles of similar status but just not sub-role.
https://output.circle-artifacts.com/output/job/8e1aeeef-348d-4532-810b-f2420c7a54a8/artifacts/0/html/team.html
xref https://github.com/astropy/astropy.github.com/issues/519
=> Roles: Sub-role in italics instead of bold

team.html
Related press releases:
* https://aas.org/press/astropy-collaboration-receive-2025-berkeley-prize
* https://www.stsci.edu/contents/news-releases/2024/news-2024-401
Preview: https://output.circle-artifacts.com/output/job/daacdd68-e195-44d1-a7a1-4eaf477e11f2/artifacts/0/html/team.html#awards
Congratulations, Astropy!
=> Astropy: 2025 Lancelot M. Berkeley–New York Community Trust Prize for Meritorious Work in Astronomy

index.html, team.html
We should highlight the prestigious awards of the project on the main landing page instead of burying them deep on the team page.
In addition, let's shout about the AAS Award on the front page! We can plan to remove this banner in two or three months.
=> Feature Astropy Project awards more prominently

index.html
This is really just a companion to astropy/astropy#16555 to synchronize what's on the web site with whatever that settles on.  Please have discussion about what we should actually recommend in astropy/astropy#16555 so that we don't spread it around multiple threads. 
Rendered doc: https://output.circle-artifacts.com/output/job/fc974b2f-31be-45e0-a824-116fb2da9647/artifacts/0/html/index.html
=> Change mention of conda (was: change conda to miniforge)

index.html
When I showed the `astropy.org` landing page to someone (for the new award stuff), their first comment was "Why is the astropy version number `"6.1?"`?  Don't they know the version number? I actually had the same feeling looking at this, since the question mark is in the same color due to being in the link reference.
One option is moving the question mark outside the link so it appears black, but I think that looks awkward. So this PR just removes it entirely, following the [example of Python](https://docs.python.org/3/whatsnew/index.html), like `What's new in Astropy 6.1` as a statement not a question.
=> Remove question mark in What's new

about.html, acknowledging.html, announcements/release-0.4.html, announcements/release-1.0.html, announcements/release-1.1.html, announcements/release-1.2.html, announcements/release-1.3.html, announcements/release-2.0.html, announcements/release-3.0.html, announcements/release-3.1.html, announcements/release-3.2.html, announcements/release-4.0.html, announcements/release-4.1.html, announcements/release-4.3.html, announcements/release-5.0.html, announcements/release-5.1.html, announcements/release-5.2.html, announcements/release-5.3.html, announcements/release-6.0.html, announcements/release-6.1.html, code_of_conduct.html, contribute.html, credits.html, help.html, history.html, index.html, roles.json, team.html
Fix #610
Just a blind search and replace: `find ./ -type f -exec sed -i 's/http:\/\/docs\.astropy/https:\/\/docs\.astropy/g' {} \;`
=> Use HTTPS for docs.astropy.org URLs

credits.html
This started as a PR to fix a typo ("He also is as a maintainer"), but I also reworded it a bit.
=> Update description in lifetime contributors

roles.json
Adding @neutrinoceros in this role, to facilitate his work in his present position as research software engineer and beyond that.
=> Add Clement Robert as general maintainer for Astropy core

roles.json
In https://github.com/astropy/astropy.github.com/pull/475 , there is no explanation why they couldn't be in the same section. Seems weird to have almost duplicate text as different rows. But is it allowed to have "sub-roles" and "responsibilities" not match?
https://output.circle-artifacts.com/output/job/e76af6f1-9bbd-4d0f-bb6f-02e3374ff603/artifacts/0/html/team.html
xref https://github.com/astropy/astropy.github.com/issues/519
=> Roles: Move general maintainers in same section as sub-package maintainers

roles.json
I finally got around to "Step 1" from the [roles breakout session from Astropy Coordination Meeting 2023](https://docs.google.com/document/d/1sBImbw1p4mM3VYWGQJDRbj2N3uqP5Ed_Wfb8BDjJj2o/edit#heading=h.lap2vjp9ad1z).
Who attended: me, @eteq, @hamogu, @weaverba137, @aaryapatil, @saimn 
Exact notes that is relevant here:
* Expand infrastructure
* Change Specialist to Project Infrastructure Tech Lead and reduce scope to "set up and maintain CI” and “moving between repo" because others are covered by “core” roles already.
* Have sub-roles according to broad categories w.r.t. [flow chart from State of Infrastructure this morning](https://docs.google.com/presentation/d/131opPCTy5OWz74G7K88iDn8n3pePSCbjQ5QdHVn7Ckw/edit#slide=id.g23c3c3dc480_0_57).
My interpretation of those notes is this PR.
Out …
=> Roles: Consolidate infrastructure roles

roles.json
I am nominating @jeffjennings to join the Learn team. He is in the process of getting up to speed and fixing the broken infrastructure of the Learn Astropy website and will be a great addition to the team.
=> Add Jeff Jennings to Learn

roles.json
This came out of some discussions the CoCo has been having the last few months on whose role it is to do big picture planning.  We eventually settled on the reality of the current situation: that it has historically been something the CoCo does, but it is not *necessary* that this be so, and we should make it an explicit role so others can participate if they want.
As a starting point I named the people as just "the CoCo members" since that's the current reality, but that could change if others want to lean in on this topic.
=> Add strategic planning role

team.html
Remove duplicate Ed Slavich because it is the same as Edward Slavich.
Pinging @astropy/astropy-project-release-team because I think this list is updated during releases?
=> Remove duplicate Ed Slavich

affiliated/index.html, getteam.py, history.html, js/functions.js, team.html
Seems like every page is trying to read `roles.json`. This even results in error in console log because `affiliated/index.html` cannot find `roles.json` in its own directory. Really only the Team page should be parsing `roles.json`.
Also fix #642 
And fix an error on History page (lol).
=> Only parse roles.json on Team page + other fixes

roles.json
@hpparvi was hired as Specreduce project manager, and has accepted the role as maintainer and started these duties, so I am adding him to the roles page as a maintainer.
=> Add Hannu Parviainen as specreduce maintainer

affiliated/index.html
Recently made possible by https://github.com/pyOpenSci/pyopensci.github.io/pull/207
=> Update link to pyOpenSci partners page for Astropy

index.html
Per the memo from Karla Smith Jackson "Initial Guidance Regarding Diversity, Equity, Inclusion, Accessibility (DEIA) Executive Orders", this changes the community code of conduct link reference on the astropy.org landing page. Astropy has two NASA grants which fall under the jurisdiction of the order based on other email guidance.
=> Update index.html per Executive Order

affiliated/index.html, js/functions.js
Having a 4th package (congrats) via our pyOpenSci partnership broke the parser with IndexError. Not sure why index math worked for the old listing but not for the new one. Just using `-1` to append should be good enough.
=> BUG: Fix IndexError in pyos insertRow

affiliated/index.html
As suggested in https://github.com/astropy/astropy.github.com/pull/550#issuecomment-2695927891 . Also see:
* https://github.com/pyOpenSci/pyopensci.github.io/pull/576
=> pyOpenSci affiliated package listing: Use labels instead of partners field

js/analytics.js
For the current website analytics, Google analytics suggests updating the old measurement ID to a new format because "Legacy UA tags with connected site tags could lead to inconsistent data reports". This PR updates the measurement ID from "UA-*" to the new identifier. I've verified that it is not an issue for the measurement ID to be public, as it has been.
=> Update google analytics measurement ID

annoucement_banner.html, index.html
#653 added a banner to announce the astropy user survey. As promised there, this PR removes the banner after being live for 1 month. 
Fix #654
=> Remove survey banner

index.html
Example gallery in core lib never really took off, so it was removed. The link will be broken when astropy v7.1 is released.
* astropy/astropy#17270 
* astropy/astropy#16194
=> Remove defunct example gallery from Learn section

roles.json
This PR is to name the chair of the finance committee following the policy change proposed in [PR#467](https://github.com/astropy/astropy-project/pull/467).
=> Add chair role to the finance committee

team.html
The PR changes the following 4 voting members to emeritus status:
- E. Madison Bray
- Michael Droettboom
- Zé Vinícius
- Juan Luis Cano Rodríguez
All new emeritus members have been contacted and agreed to the change in status.
=> Changing inactive voting members to emeritus status

index.html, roles.json
Updates the hyperlinks to the Learn site, as they were broken at https://www.astropy.org/ and https://www.astropy.org/team.html. 
Fix #666
=> Update learn link
