astropy/astropy.github.com

announcements/release-1.0.html, index.html
cc @astropy/astropy-core-maintainers
=> Changes for v1.0 release, including announcement

index.html
In preparation for release--to be merged after release.
=> Update latest version on index to v1.0.2

affiliated/index.html, announcements/release-0.4.html, announcements/release-1.0.html, contribute.html, help.html
Fixes issue #61.
Will be great to get some sort of template system going for the Astropy website like we used to have...? :D
=> Fixed up use of new hi-res logo on a few sub-pages.

.travis.yml
Also, everyone loves it when Travis says it's ok to merge. Even if the changes are unrelated.
=> Added Travis to validate JSON file

about.html, css/style.css
If/when astropy/astropy-APEs#11 is adopted, this PR will add the code of conduct to the web site.
=> add code of conduct

affiliated/registry.json
=> Add spectral-cube to registry

affiliated/index.html
link to bottom of page when it is mentioned
=> affiliated: add a link

affiliated/index.html, js/functions.js
=> Fixes #42 seperates the table based on provisional column

about.html, affiliated/index.html, announcements/release-0.4.html, announcements/release-1.0.html, contribute.html, help.html, index.html
That way viewing the website through https will work.
Fix #74.
=> Use HTTPS for external JS and fonts.

affiliated/registry.json
This PR updates the status of the ccdproc API to stable and adds me as one of the authors. Will close astropy/ccdproc#286 when merged. (ping @crawfordsm)
=> Update authors and API status of ccdproc

index.html
Should be merged once we are ready to announce
=> Updates for v1.2 release

announcements/release-1.2.html
=> Added 1.2 announcement

team.html
I wasn't listed as contributor.
=> Add one more contributor

roles.txt, team.html
=> Swap Larry B. and Tom R. roles in visualization subpackage

affiliated/registry.json
I need to update my email address as maintainer of PyDL.
=> update email address

contribute.html
This was done already for the help page.
=> Remove the freenode channel and add gitter instead

team.html
Somehow the top 2 contributors were missing from the list...
=> Adding two missing names and remove duplicate from contributor list

affiliated/registry.json
Replaces https://github.com/astropy/astropy.github.com/pull/101
=> Add cluster-lensing as provisional affiliated package

team.html
=> Add Christoph Deil as lead maintainer for MacPorts distribution coordinator

index.html
As @abostroem said in #159, this shouldn't cause too much trouble, but it's still better to do via a PR than directly pushed to master.
=> Update astropy version to 1.3.3 and LTS to 1.0.13

css/style.css, help.html, index.html
=> Improving readability and links to help

affiliated/index.html
=> Fix last name typo for Ginga maintainer

affiliated/registry.json
See spacetelescope/spherical_geometry#104. xref mwcraig/astropy-affiliated-numfocus-blog#9.
c/c @bernie-simon
=> Renamed sphere to spherical_geometry

roles.txt
As discussed in coordination meeting. c/c @taldcroft @stargaser @mhvk
=> Update constants maintainers

affiliated/registry.json
Removed a stray period, added a link.
=> Update Gala entry

.travis.yml, affiliated/registry.json
I know we are going to overhaul this page soon, but just to make sure accepted packages are indeed marked as accepted
=> Update accepted affiliated packages

css/style.css, index.html
This simplifies the Install Astropy instructions and adds some cross-reference links.
=> Improve astropy.org landing page

index.html
This is a relatively big change - I would like to propose updating the mission statement. The original statement made it sound like we just developed a single package and just helped other packages be interoperable. This is clearly no longer the case - we as a community are coordinating the development of several packages including but not limited to the core package. Preview of the new statement:
I also think we may want to consider updating the tag line in the logo, or even removing it altogether (now that most people would recognize the actual logo bit on the left). We may actually want to have a logo that says 'The Astropy Project' instead and then have a version that has astropy in lowercase for the package (but the logo stuff could be done separately - let's focus on the mission …
=> Update mission statement

affiliated/registry.json
Includes the changes from https://github.com/mwcraig/astropy-affiliated-numfocus-blog/pull/14
=> Propagate update of specutils maintainers/description

affiliated/registry.json
The reviews for these have been sent out
=> Updated accepted packages

roles.txt, team.html
@kelle - please have a look.  We need some text describing the roles, could you help me out?  You can just put it here as a comment if that's easiest.
=> WIP: add Astropy Learn and testing coordinator roles

affiliated/registry.json
Add `synphot` to affiliated package registry.
=> Add synphot to affiliated package registry

index.html
Tutorials button should point to http://astropy-tutorials.readthedocs.io/en/latest/
=> Update link to the tutorials webpage

affiliated/registry.json
=> Added saba to registry

acknowledging.html, announcements/release-0.4.html, announcements/release-1.0.html, announcements/release-1.1.html, announcements/release-1.2.html, announcements/release-1.3.html, announcements/release-2.0.html, announcements/release-3.0.html
Same as https://github.com/astropy/astropy/pull/7460 ;-)
=> Hyperlink DOIs against preferred resolver

affiliated/registry.json
=> Fix URL keys for Saba affiliated package

roles.json
=> Fix Dan's last name

roles.json
As requested by @sfabbro via private communication. cc @astropy/coordinators
=> Update Gentoo lead

.circleci/config.yml
=> Use giles to get a preview of the website

affiliated/registry.json
Pull request requested here https://github.com/toros-astro/corral/issues/28
=> Pull request for Corral Package

affiliated/index.html, js/functions.js
Fixes #262 
Enumerated affiliated packages and total number is shown on top of table.
@eteq @bsipocz Please have a look.
=> Fix #262: Add total number of affiliated packages

LICENSE.rst
I guess we should leave this open for a couple of weeks in case any contributors have objections.
Since in principle this would require agreement from all contributors, as a middle ground I'll ping the top 10 contributors (according to GitHub): @eteq @taldcroft @granttremblay @mdboom @bsipocz @abostroem @kelle @pllim @embray - feel free to ignore if you don't care or are happy with this - just put a comment if you object.
Fixes https://github.com/astropy/astropy.github.com/issues/198
=> Added license

affiliated/registry.json
Small change to the affiliated package registry.
=> Improve the description of pyspeckit

about.html
=> Fix broken license link in the astropy site

affiliated/registry.json
@jakevdp - not sure whether your e-mail address still works, so I've changed that one.  Let me know if you prefer to have yours listed instead.
=> Adding new maintainer and fix spelling

roles.json
I assume this is the right place?
=> Add me to pacakge template maintainer

contribute.html
I didn't remove the item itself. Fixes #308.
=> Remove userecho link since it is no longer used

announcements/release-3.2.html, index.html
Note that #328 already updated the team
=> Release updates for 3.2

affiliated/index.html, affiliated/registry.json, announcements/release-2.0.html, announcements/release-3.0.html, announcements/release-3.1.html, announcements/release-3.2.html, css/style.css, index.html, js/functions.js
* Removed fontawesome CSS which I think is no longer needed
* Fixed vertical spacing in affiliated package table
* Fixed first column of affiliated package table which was too wide
=> Aesthetic fixes to website

affiliated/registry.json
EinsteinPy is an open source pure Python package dedicated to problems arising in General Relativity, relativistic physics and gravitational astronomy, such as goedesics plotting for schwarzschild space-time model, calculation of schwarzschild radius for any mass given, symbolic calculation of various functions related to GR such as christoffel symbols. Features like visualization of geodesics of curved black holes and 3D visualizations are some of the features which are planned. It is released under the MIT license. 
Documentation: https://docs.einsteinpy.org
=> Proposed affiliated package: EinsteinPy

affiliated/registry.json, affiliated/validate_registry.py, js/functions.js
Previously this was confusing since 'Partial' really meant 'No'
=> Use Yes/No for Python 3 support

affiliated/registry.json
This PR sets the `pypi_name` and `provisional` fields for sbpy.
The package is on Pypi ([tested](https://pypi.org/project/sbpy/)), and this is mentioned in the `README.md`.
For `provisional` I just assumed that it is non-provisional since this status is nowhere mentioned. BTW, the [review docs](https://github.com/astropy/astropy-procedures/blob/65d45d3d48ea0f4629c5e565a10479d009e54928/documents/affiliated_package_review_guidelines.md) do not mention the `provisional` status flag -- what are the criteria here?
=> Complete the record for sbpy affiliated package

affiliated/registry.json
This PR proposes to update the entry for pyvo and much happened since May:
* adding the new maintainers to the page
* version v1.0  is out
* the package is actively developed. whether it falls into the "heavy development" or "good" category is a question to decide, looking at the list of the rest of the packages I would go with "good".
=> Updating pyvo in affiliated list

about.html, contribute.html
This PR updates language about NumFOCUS to use the new standard.
Fixes #338
=> Update language for NumFOCUS

announcements/release-4.0.html, index.html, team.html
What with merging until the announcement is ready to go!
=> Updating version number to 4.0

affiliated/registry.json
This is because I was not able to push to the branch in https://github.com/astropy/astropy.github.com/pull/319
Fixes #319
=> Added entry for affiliated package mocpy

affiliated/registry.json, roles.json
Just what it says on the tin, as per out-of-band discussions.   @ceb8 and @bsipocz please approve or 👍 just so we're sure you're aware!
=> Add clara brasseur as astroquery maintainer

js/functions.js, roles.json, team.html, validate_roles.py
As decided at the Coordination meeting in Socorro. I'll also email astropy-core-maintainers to let people know about the change (done!)
Fixes #364
=> Merge deputy and lead roles

acknowledging.html
I think this fixes the last remaining point in astropy/astropy#7297
=> Add some text to recommend using \software{} tag in latex (for AAS journals)

roles.json
=> roles update for crawford resignation

roles.json
=> Added Simon Conseil to infrastructure roles

roles.json
@mcara is to be added to as a wcs co-maintainer
=> Add cara to wcs

index.html
=> Update current version to v4.0.2

roles.json
As discussed on the mailing list.
(At the time of merging this, the confidential@astropy.org email will also be updated to go to the new ombudsperson)
=> add perry greenfield as ombudsperson

index.html
=> Update current version to v4.0.3

affiliated/registry.json
Hello,
Please consider my PR, I updated information of the astroalign project. I basically changed affiliation and moved the repo to a different organization.
I also updated my contact information to a more stable email.
Thanks,
Martin.
=> Updated astroalign

affiliated/registry.json
Close #421 .
Also see #315 .
cc @vrodgom
=> statmorpth: update from re-review

index.html
=> update for 4.2.1

roles.json
Trivial changes for consistency
=> Finance ctte role update

roles.json
Note that this shouldn't be merged yet as I need to email astropy-dev following the new process.
=> Added Stuart Mumford as reproject maintainer

team.html
Note this is for those of the "initial" cohort who responded after #431 was merged (up to today, at least!)
cc @Cadair @ceb8 @mwcraig
=> Updated voting member list

index.html
Just what it says in the tin.  Should not be merged until conda-forge at least is working.
=> update web site for 4.3

announcements/release-4.3.html
Just what it says on the tin.
Note we are missing a release announcement for 4.2 on the page - not sure what happened there.  But probably not worth worrying about it at this point - I copied this one over from 4.1.  Once this has gotten a review, I'll plan to send out the message announcements once it's merged.
=> add 4.3 announcement

roles.json
Congratulations to the new CoCo members! :tada:
=> Update the CoCo members following the 2021 elections

help.html
This update adds the OpenAstronomy discourse server to the help section and updates the explanation of slack.
=> Update help section on astropy website

roles.json
Sadly reflecting on paper the current reality 😢 Already sent an email to `coordinators@` giving more details about my reasoning and expressing my gratitude and appreciation for the project.
=> Remove Juan Luis from astropy.coordinates

affiliated/registry.json
but you shouldn't trust my date-and-time proficiency...
Fixes #462
=> Get Omnifit update date right

affiliated/registry.json
From the abstract of our paper (DOI : 10.1016/j.ascom.2021.100503) we cite:
BayesicFitting is a comprehensive, general-purpose toolbox for simple and standardized model fitting. Its fitting options range from simple least-squares methods, via maximum likelihood to fully Bayesian inference, working on a multitude of available models. BayesicFitting is open source and has been in development and use since the 1990s. It has been applied to a variety of science applications, chiefly in astronomy.
BayesicFitting consists of a collection of PYTHON classes that can be combined to solve quite complicated inference problems. Amongst the classes are models, fitters, priors, error distributions, engines, samples, and of course NestedSampler, our general-purpose implementation of the nested sampling …
=> Proposed affiliated package: BayesicFitting

affiliated/index.html
Add words about including citation instructions and citing other relevant works. Includes a link to the AstroBetter post about citing software.
=> Add bullet about citation to affiliated package guidelines.

index.html
=> Updated core package version to 5.0.1

credits.html
Based on answers to the 2020/01 roles survey.
=> Add Adam Ginsburg to lifetime contributors

credits.html
This is based on answers to the 2022/01 roles survey.
=> Add Matt Craig to lifetime contributors

affiliated/registry.json
=> Update specutils maintainers

affiliated/registry.json
Oxford comma! Should be uncontroversial? 
Actually, do we need to order by last name alphabetically?
=> Use Oxford comma for Einsteinpy

affiliated/registry.json
=> Update spherical-geometry maintainer

affiliated/registry.json
=> Add myself as co-maintainer of spectral-cube

affiliated/registry.json
Added Tom D but also found a typo in Adrian D's name.
=> Update pyvo maintainers

affiliated/registry.json
=> Fix maintainer name for pllim

affiliated/registry.json
This is to mirrror a change at astropy/astropy-v5.0-paper#81 . I think we should formalize it here first before putting that on the paper.
mocpy was added in #366
=> Update mocpy maintainer list

affiliated/registry.json
lenstronomy just moved to an organization repository and the developer and maintainer list has widened.
This PR reflects these changes.
I have not changed the 'latest updated' date since this PR does not reflect a change of status.
Let me know if you wish me change anything.
Thank you very much!
Simon
=> updated lenstronomy developer names and repository

acknowledging.html
This adds the bibtex for Paper 3 to the Acknowledging and Citing Astropy page.
=> Add citation for Paper 3

getteam.py, team.html
This also fixes the script used to update the page
=> Update team following v5.2 release of core package

index.html
=> Updated version on front page

about.html, team.html
=> List past Astropy awards received

roles.json
As requested by Médéric Boquien via email, "I need my name to be removed from the list of distribution coordinators."
@mboquien , please approve if indeed this is what you wish. Thank you!
=> Remove Médéric Boquien as requested

index.html
Fix https://github.com/astropy/astropy/issues/14892
=> Update whatsnew link to v5.3

roles.json
Add Beryl as new Community Manager
=> Adding Beryl Kanali as new CM

team.html
=> Adding new voting members after December 2023 election

help.html
I'm not entirely sure this is correct but it looks reasonable to me.
=> Fix unterminated string literal

README.md
It's been 3 years so I think it's safe to do this!
=> remove the warning about master->main

affiliated/index.html
Fix https://github.com/astropy/astropy.github.com/issues/580
=> APE 22: Add link to packages under review

roles.json
Just what it says on the tin!  Note this is a follow-up of #309, as @astrofrog realized there that he was willing to take on this role
=> Add Thomas Robitaille as fits maintainer

roles.json
I have self-nominated/volunteered to take on the unfilled Learn Coordinator role.
=> Add Clara Brasseur as Learn coordinator

roles.json
Ref:
* https://github.com/astropy/astropy-project/pull/284
* https://github.com/astropy/astropy-project/pull/391
Reverts #557
=> Beryl's contract ended as Community Manager

affiliated/index.html
As suggested by @sneakers-the-rat  in https://github.com/astropy/astropy.github.com/pull/605#issuecomment-2223679001 . Thanks!
=> APE 22 listing: Simplify found_astropy

roles.json
See also https://github.com/astropy/astropy-project/issues/435
Fix https://github.com/astropy/astropy-project/issues/435
=> Add @svank as a reproject maintainer

about.html
Fix https://github.com/astropy/astropy.github.com/issues/618
Rendered doc: https://output.circle-artifacts.com/output/job/eccbce8f-9fc3-40da-ace7-b2814c2cf443/artifacts/0/html/about.html#governance
=> Add a blurb about governance

credits.html
Remove unused CSS from credits page and fixes missing tags and see if that fixes the broken permalink.
Not sure why permalink not showing up at https://www.astropy.org/credits.html
=> Fix permalinks on Credits page

acknowledging.html, index.html, paper1_10k_citation.html
To close https://github.com/astropy/astropy-project/issues/431
=> 10k citations press release

roles.json
Fix #632 
Rendered doc: https://output.circle-artifacts.com/output/job/6ba9135c-9d7e-4064-889f-0d3463690878/artifacts/0/html/team.html
=> Remove Twitter role and update Community Engagement descriptions

credits.html
Add mention of new NASA grant for Open-Source Tools, Frameworks, and Libraries foundation award 2024.
Fix https://github.com/astropy/astropy.github.com/issues/635
Preview: https://output.circle-artifacts.com/output/job/5358bcc4-9231-44fb-baad-11c7b5ecc3d0/artifacts/0/html/credits.html#institutional-support
=> Add mention of new NASA grant

roles.json
Membership and Running Notes link
=> Update Roles descriptions to CoCo6

affiliated/registry.json
Update halotools maintainer list to include @nvanalfen. Thanks to @pllim for suggesting this.
=> Update halotools maintainer list

affiliated/index.html
xref https://github.com/pyOpenSci/pyopensci.github.io/issues/562
Thanks to @kecnry for the help!
=> Sort pyos listing alphabetically, case-insensitive

credits.html
=> Add credits for Gemini

credits.html
=> Add a credit for IPAC

affiliated/registry.json, roles.json
Add @Cadair as a maintainer for https://github.com/astropy/asdf-astropy
=> Add Stuart Mumford as asdf-astropy maintainer
